---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dongyf.
--- DateTime: 2018/11/6 上午10:20
---

local Workbook = require "xlsxwriter.workbook"
local utils = require("resty.utils.utils")
local _M = {}

--[[
    @brief:
            生成xls文档
    @params:
            file_name 文件名
            sheet_name 工作表名
            rows 行数 不包含行头
            cols 列数 不包含列头
            row_header 行头
            col_header 列头
            offset_x 偏移左上角x坐标
            offset_y 偏移左上角y坐标
            data 数据
                {
                    '1_1' = xxxx
                    '1_2' = xxxx

                }
    @return:
            true
            nil
]]
_M.generate_xls_file = function (file_name, sheet_name, rows, cols,
                                 row_header, col_header, offset_x, offset_y, data)
    if not file_name then
        return nil, 'file_name 参数错误.'
    end

    if tonumber(rows) == nil or tonumber(rows) <= 0  then
        return nil, 'rows 参数错误.'
    end

    if tonumber(cols) == nil or tonumber(cols) <= 0  then
        return nil, 'cols 参数错误.'
    end

    if tonumber(offset_x) == nil or tonumber(offset_x) < 0 then
        offset_x = 0
    end

    if tonumber(offset_y) == nil or tonumber(offset_y) < 0 then
        offset_y = 0
    end

    if #row_header ~= tonumber(rows) then
        return nil, 'row_header 参数错误. row_header 内容数量与rows不一致.'
    end

    if #col_header ~= tonumber(cols) then
        return nil, 'col_header 参数错误. col_header 内容数量与cols不一致.'
    end

    --if #data ~= (tonumber(rows) * tonumber(cols)) then
    --    return nil, 'data 参数错误. data 内容数量与rows * cols不一致.'
    --end

    --创建xls文件
    local workbook = Workbook:new(file_name, {constant_memory = true})
    --创建xls工作sheet
    local worksheet = workbook:add_worksheet(sheet_name)
    --设置单元格 数据格式
    local bold = workbook:add_format({bold = true}) -- Add a number format for cells with money.
    local money = workbook:add_format({num_format = "￥#,###,###,##0"})


    for row = 0, tonumber(rows) do
        for col = 0, tonumber(cols) do
            if row == 0 then
                if col ~= 0 then
                    worksheet:write((row + offset_x), (col + offset_y), col_header[col], bold)
                end
            else
                if col == 0 then
                    worksheet:write((row + offset_x), (col + offset_y), row_header[row], bold)
                end
            end
            local idx = row .. '_' .. col
            if data[idx] then
                worksheet:write((row + offset_x), (col + offset_y), data[idx], money)
            end
        end
    end

    workbook:close()

    return true
end


return _M